import '../scss/style.scss';
import '../scss/normalize.scss';
import '../scss/variables.scss';
import '../scss/site-navigation/site-navigation.scss';
import '../scss/containerCommunications/containerCommunications.scss';
import '../scss/title-index/title-index.scss';
import '../scss/menu/menu.scss';
import '../scss/main-content/main-content.scss';
import '../scss/site-headers/site-headers.scss';
import '../scss/swiper/swiper.min.scss';
import '../scss/swiper/styleSwiper.scss';
import '../scss/swiper/default-styles.scss';
import '../scss/hide-button/hide-button.scss';
import '../scss/interactive-button/interactive-button.scss';
import '../scss/signature/signature.scss';
import '../scss/sentence/sentence.scss';
import '../scss/basement/basement.scss';
import '../scss/mobile-nav/mobile-nav.scss';
import '../scss/info/info.scss';
import '../scss/popup/popup.scss';
import '../scss/feedback/feedback.scss';
import '../scss/contract/contract.scss';
import '../scss/centermen/centermen.scss';
import '../scss/centermen-main/centermen-main.scss';
import '../js/swiper.min.js';
import '../js/slider-containerBrend.js';
import '../js/slider-containerRepairs.js';
import '../js/slider-containerPrices.js';
import '../js/script-button.js';
import '../js/mobile-nav.js';


console.log('Works!');
